import { ChakraProvider } from "@chakra-ui/react";
import Head from "next/head";
import theme from "../styles/theme";
import { AppProps } from "next/app";
import { SessionProvider } from "next-auth/react";
import NavBar from "../layout/NavBar";
import Footer from "../layout/Footer";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SessionProvider session={pageProps.session} refetchInterval={0}>
        <ChakraProvider resetCSS theme={theme}>
          <NavBar />
          <Component {...pageProps} />
          <Footer />
        </ChakraProvider>
      </SessionProvider>
    </>
  );
}

export default MyApp;
